[package]
name = "proj16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
gdk = "0.16.2"
glib = "0.16.4"
glib-macros = "0.16.3"
gtk = "0.16.2"
rand = "0.8.5"
